- name: hosts
  hosts: 192.168.1.215 
  tasks: 
    - name: create partition 
      parted: 
        device: /dev/sdb 
        number: 1 
        flags: [lvm] 
        state: present
    - name: create vg
      lvg: 
        vg: vg0 
        pvs: /dev/sdb1
      when: anasible_devices.vdb.partitions.vdb1 is defined
    - name: create logical volume 
      lvol: 
        vg: vg0 
        lv: lv0
        size: 1500m 
      when: ansible_lvm.vgs.vg0 is defined and (( ansible_lvm.vgs.vg0.size_g| float)>1.5) 
    - name: send message if volume group not large enough 
      debug: 
        msg: Not enough space for logical volume 
      when: ansible_lvm.vgs.vg0 is defined and ((ansible_lvm.vgs.vg0.size_g| float)< 1.5) 
    - name: create a smaller logical volume
      lvol: 
        vg: vg0 
        lv: lv0
        size: 1500m 
      when: ansible_lvm.vgs.vg0 is defined and ((ansible_lvm.vgs.vg0.size_g|float)<1.5) 
    - name: create fs 
      filesystem: 
        dev: /dev/vg0/lv0
        fstype: xfs
      when: ansible_lvm.vgs.vg0 is defined
