---
- name: print out machine information 
  hosts: all 
  gather_facts: yes
  tasks: 
   - debug: msg="{{ ansible_nodename }} - {{ ansible_hostname }} - {{ ansible_all_ipv4_addresses }} - {{ ansible_default_ipv4['macaddress'] }} - {{ ansible_architecture }}"    


