---
- name: Generate privileged users report on all hosts
  hosts: all
  become: true
  gather_facts: false

  vars:
    remote_script_path: /tmp/privileged_users_report_rhel.sh
    remote_csv_path: /tmp/privileged_users_report.csv
    local_reports_dir: ./reports

  tasks:
    - name: Ensure local reports directory exists (on controller)
      delegate_to: localhost
      run_once: true
      file:
        path: "{{ local_reports_dir }}"
        state: directory
        mode: "0755"

    - name: Copy privileged_users_report script to remote hosts
      copy:
        src: "{{ playbook_dir }}/privileged_users_report_rhel.sh"
        dest: "{{ remote_script_path }}"
        mode: "0755"

    - name: Run privileged users report script on remote hosts
      shell: "{{ remote_script_path }} {{ remote_csv_path }}"

    - name: Ensure report CSV is world-readable on remote hosts
      file:
        path: "{{ remote_csv_path }}"
        mode: "0644"

    - name: Get FQDN of remote host
      command: hostname -f
      register: fqdn_result
      changed_when: false

    - name: Fetch CSV report from remote hosts to controller
      fetch:
        src: "{{ remote_csv_path }}"
        dest: "{{ local_reports_dir }}/{{ fqdn_result.stdout }}.csv"
        flat: yes

- name: Consolidate all host reports into one grouped file
  hosts: localhost
  gather_facts: false

  vars:
    local_reports_dir: ./reports
    consolidated_csv: ./reports/all_privileged_users.csv

  tasks:
    - name: Find per-host CSV files
      find:
        paths: "{{ local_reports_dir }}"
        patterns: "*.csv"
        excludes: "all_privileged_users.*"
        file_type: file
      register: csv_files

    - name: Fail if no CSV files were found
      fail:
        msg: "No per-host CSV files found to consolidate."
      when: csv_files.matched == 0

    - name: Initialize consolidated CSV with header
      shell: |
        echo "username,uid,groups,logins_current_month,failed_logins_current_month,violation,account_expired,created_current_month,creation_date" > "{{ consolidated_csv }}"
      args:
        executable: /bin/bash

    - name: Append host blocks to consolidated CSV
      shell: |
        host="{{ item.path | basename | regex_replace('\\.csv$','') }}"
        echo "$host,,,,,,,," >> "{{ consolidated_csv }}"
        tail -n +2 "{{ item.path }}" >> "{{ consolidated_csv }}"
      args:
        executable: /bin/bash
      loop: "{{ csv_files.files | sort(attribute='path') }}"
