---
- name: Using template - sample 
  hosts: 192.168.1.218  
  vars: 
    http_port: 80 
    domain: sunkloud.com
  tasks: 
   - name: Install apache
     yum: name=httpd state=present
   - name: create the document root 
     file: 
       path: /var/www/html/{{ domain }} 
       state: directory 
       owner: root 
       group: root 
       mode : 0755
   - name: generate the config file from template
     template: 
       src: ./templates/virtualhost.conf.j2
       dest: /etc/httpd/conf.d/virtualhost.conf
       owner: root 
       group: root 
       mode: 0644 
     notify: 
      - Restart HTTPD
   - name: opening up port 80 
     firewalld:
       service: http
       permanent: yes
       state: enabled

  handlers:          
    - name: Restart HTTPD
      service: 
        name: httpd
        state: restarted   
